(function(){var a=!1,b=/var xyz/.test(function(){})?/\b_super\b/:/[\D|\d]*/;this.__tmClass=function(){};window.__tmClass=this.__tmClass;__tmClass.extend=function(c){function f(){!a&&this.init&&this.init.apply(this,arguments)}var h=this.prototype;a=!0;var k=new this;a=!1;for(var p in c)k[p]="function"==typeof c[p]&&"function"==typeof h[p]&&b.test(c[p])?function(a,b){return function(){var c=this._super;this._super=h[a];var f=b.apply(this,arguments);this._super=c;return f}}(p,c[p]):c[p];f.prototype=
k;f.prototype.constructor=f;f.extend=arguments.callee;return window.__tmClass=f}})();window.triggermail={};window.console?"undefined"==typeof window.console.debug&&(console.debug=function(){}):console={debug:function(){},error:function(){},log:function(){}};window.TM_API_HOST="triggeredmail.appspot.com/api";window.triggermail.lytics=[];triggermail.lytics.__SV=1.2;
(function(a){function b(){b.done||(H=b.done=!0,I=!1,d.each(y,function(e){e._dom_loaded()}))}var c=Array.prototype,f=Object.prototype,h=c.slice,k=f.toString,p=f.hasOwnProperty,u=window.console,x=window.navigator,r=window.document,l=x.userAgent,C=["__mps","__mpa","__mpap","$people_distinct_id","__alias"],w=!1;try{w=window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest}catch(K){}var L="https:"==r.location.protocol?"https://":"http://",f=a&&a.__SV||0,D=w,I=!D&&-1==l.indexOf("MSIE"),d={},z=!1,
M={api_host:L+TM_API_HOST,cross_subdomain_cookie:!0,cookie_name:"",loaded:function(){},store_google:!1,save_referrer:!0,test:!1,verbose:!1,img:!1,track_pageview:!0,debug:!1,live_demo:!1,track_links_timeout:300,cookie_expiration:365,upgrade:!1,disable_cookie:!1,ip:!0},H=!1;(function(){var e=c.forEach,a=c.indexOf,m=Array.isArray,b={},G=d.each=function(a,q,m){if(null!=a)if(e&&a.forEach===e)a.forEach(q,m);else if(a.length===+a.length)for(var d=0,c=a.length;d<c&&!(d in a&&q.call(m,a[d],d,a)===b);d++);
else for(d in a)if(p.call(a,d)&&q.call(m,a[d],d,a)===b)break};d.extend=function(e){G(h.call(arguments,1),function(a){for(var q in a)void 0!==a[q]&&(e[q]=a[q])});return e};d.isArray=m||function(e){return"[object Array]"===k.call(e)};d.isFunction=function(e){try{return/^\s*\bfunction\b/.test(e)}catch(a){return!1}};d.isArguments=function(e){return!(!e||!p.call(e,"callee"))};d.toArray=function(e){return!e?[]:e.toArray?e.toArray():d.isArray(e)||d.isArguments(e)?h.call(e):d.values(e)};d.values=function(e){var a=
[];if(null==e)return a;G(e,function(e){a[a.length]=e});return a};d.identity=function(e){return e};d.include=function(e,m){var d=!1;if(null==e)return d;if(a&&e.indexOf===a)return-1!=e.indexOf(m);G(e,function(e){if(d||(d=e===m))return b});return d};d.includes=function(e,a){return-1!==e.indexOf(a)}})();d.inherit=function(e,a){e.prototype=new a;e.prototype.constructor=e;e.superclass=a.prototype;return e};d.isObject=function(e){return e===Object(e)&&!d.isArray(e)};d.isEmptyObject=function(e){if(d.isObject(e)){for(var a in e)if(p.call(e,
a))return!1;return!0}return!1};d.isUndefined=function(e){return void 0===e};d.isString=function(e){return"[object String]"==k.call(e)};d.isDate=function(e){return"[object Date]"==k.call(e)};d.isNumber=function(e){return"[object Number]"==k.call(e)};d.encodeDates=function(e){d.each(e,function(a,m){d.isDate(a)?e[m]=d.formatDate(a):d.isObject(a)&&(e[m]=d.encodeDates(a))});return e};d.formatDate=function(e){function a(e){return 10>e?"0"+e:e}return e.getUTCFullYear()+"-"+a(e.getUTCMonth()+1)+"-"+a(e.getUTCDate())+
"T"+a(e.getUTCHours())+":"+a(e.getUTCMinutes())+":"+a(e.getUTCSeconds())};d.strip_empty_properties=function(e){var a={};d.each(e,function(e,b){d.isString(e)&&0<e.length&&(a[b]=e)});return a};d.truncate=function(e,a){var m;"string"===typeof e?m=e.slice(0,a):d.isArray(e)?(m=[],d.each(e,function(e){m.push(d.truncate(e,a))})):d.isObject(e)?(m={},d.each(e,function(e,b){m[b]=d.truncate(e,a)})):m=e;return m};d.JSONEncode=function(){return function(e){var a=function(e){var a=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
q={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};a.lastIndex=0;return a.test(e)?'"'+e.replace(a,function(e){var a=q[e];return"string"===typeof a?a:"\\u"+("0000"+e.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+e+'"'},m=function(e,b){var d="",c=0,f=c="",f=0,h=d,g=[],t=b[e];switch(typeof t){case "string":return a(t);case "number":return isFinite(t)?String(t):"null";case "boolean":case "null":return String(t);case "object":if(!t)return"null";d+="    ";g=[];if("[object Array]"===
k.apply(t)){f=t.length;for(c=0;c<f;c+=1)g[c]=m(c,t)||"null";return f=0===g.length?"[]":d?"[\n"+d+g.join(",\n"+d)+"\n"+h+"]":"["+g.join(",")+"]"}for(c in t)p.call(t,c)&&(f=m(c,t))&&g.push(a(c)+(d?": ":":")+f);return f=0===g.length?"{}":d?"{"+g.join(",")+""+h+"}":"{"+g.join(",")+"}"}};return m("",{"":e})}}();d.JSONDecode=function(){var e,a,m={'"':'"',"\\":"\\","/":"/",b:"\b",f:"\f",n:"\n",r:"\r",t:"\t"},d,b=function(a){throw{name:"SyntaxError",message:a,at:e,text:d};},c=function(m){m&&m!==a&&b("Expected '"+
m+"' instead of '"+a+"'");a=d.charAt(e);e+=1;return a},f=function(){var e;e="";"-"===a&&(e="-",c("-"));for(;"0"<=a&&"9">=a;)e+=a,c();if("."===a)for(e+=".";c()&&"0"<=a&&"9">=a;)e+=a;if("e"===a||"E"===a){e+=a;c();if("-"===a||"+"===a)e+=a,c();for(;"0"<=a&&"9">=a;)e+=a,c()}e=+e;if(isFinite(e))return e;b("Bad number")},g=function(){var e,d,A="",f;if('"'===a)for(;c();){if('"'===a)return c(),A;if("\\"===a)if(c(),"u"===a){for(d=f=0;4>d;d+=1){e=parseInt(c(),16);if(!isFinite(e))break;f=16*f+e}A+=String.fromCharCode(f)}else if("string"===
typeof m[a])A+=m[a];else break;else A+=a}b("Bad string")},h=function(){for(;a&&" ">=a;)c()},k=function(){switch(a){case "t":return c("t"),c("r"),c("u"),c("e"),!0;case "f":return c("f"),c("a"),c("l"),c("s"),c("e"),!1;case "n":return c("n"),c("u"),c("l"),c("l"),null}b("Unexpected '"+a+"'")},t;t=function(){h();switch(a){case "{":var e;a:{var d={};if("{"===a){c("{");h();if("}"===a){c("}");e=d;break a}for(;a;){e=g();h();c(":");Object.hasOwnProperty.call(d,e)&&b('Duplicate key "'+e+'"');d[e]=t();h();if("}"===
a){c("}");e=d;break a}c(",");h()}}b("Bad object");e=void 0}return e;case "[":a:{e=[];if("["===a){c("[");h();if("]"===a){c("]");break a}for(;a;){e.push(t());h();if("]"===a){c("]");break a}c(",");h()}}b("Bad array");e=void 0}return e;case '"':return g();case "-":return f();default:return"0"<=a&&"9">=a?f():k()}};return function(m){d=m;e=0;a=" ";m=t();h();a&&b("Syntax error");return m}}();d.base64Encode=function(e){var a,m,b,c,f=0,h=0,g="",g=[];if(!e)return e;e=d.utf8Encode(e);do a=e.charCodeAt(f++),
m=e.charCodeAt(f++),b=e.charCodeAt(f++),c=a<<16|m<<8|b,a=c>>18&63,m=c>>12&63,b=c>>6&63,c&=63,g[h++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(m)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c);while(f<e.length);g=g.join("");switch(e.length%3){case 1:g=g.slice(0,-2)+"==";break;case 2:g=
g.slice(0,-1)+"="}return g};d.utf8Encode=function(e){e=(e+"").replace(/\r\n/g,"\n").replace(/\r/g,"\n");var a="",d,b,c=0,f;d=b=0;c=e.length;for(f=0;f<c;f++){var g=e.charCodeAt(f),h=null;128>g?b++:h=127<g&&2048>g?String.fromCharCode(g>>6|192,g&63|128):String.fromCharCode(g>>12|224,g>>6&63|128,g&63|128);null!==h&&(b>d&&(a+=e.substring(d,b)),a+=h,d=b=f+1)}b>d&&(a+=e.substring(d,e.length));return a};d.UUID=function(){var e=function(){for(var e=1*new Date,a=0;e==1*new Date;)a++;return e.toString(16)+a.toString(16)},
a=function(e){function a(e,d){var c,m=0;for(c=0;c<d.length;c++)m|=b[c]<<8*c;return e^m}var d,b=[],c=0;for(e=0;e<l.length;e++)d=l.charCodeAt(e),b.unshift(d&255),4<=b.length&&(c=a(c,b),b=[]);0<b.length&&(c=a(c,b));return c.toString(16)};return function(){var d=(screen.height*screen.width).toString(16);return e()+"-"+Math.random().toString(16).replace(".","")+"-"+a()+"-"+d+"-"+e()}}();d.isBlockedUA=function(){return/(google web preview|baiduspider|yandexbot)/i.test(l)?!0:!1};d.HTTPBuildQuery=function(e,
a){var b,c,f=[];"undefined"===typeof a&&(a="&");d.each(e,function(e,a){b=encodeURIComponent(e.toString());c=encodeURIComponent(a);f[f.length]=c+"="+b});return f.join(a)};d.getQueryParam=function(e,a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var d=RegExp("[\\?&]"+a+"=([^&#]*)").exec(e);return null===d||d&&"string"!==typeof d[1]&&d[1].length?"":decodeURIComponent(d[1]).replace(/\+/g," ")};d.cookie={get:function(e){e+="=";for(var a=r.cookie.split(";"),d=0;d<a.length;d++){for(var b=a[d];" "==b.charAt(0);)b=
b.substring(1,b.length);if(0==b.indexOf(e))return decodeURIComponent(b.substring(e.length,b.length))}return null},parse:function(e){var a;try{a=d.JSONDecode(d.cookie.get(e))||{}}catch(b){}return a},set:function(e,a,d,b){var c="",f="";b&&(c=(c=(c=r.location.hostname.match(/[a-z0-9][a-z0-9\-]+\.[a-z\.]{2,6}$/i))?c[0]:"")?"; domain=."+c:"");d&&(f=new Date,f.setTime(f.getTime()+864E5*d),f="; expires="+f.toGMTString());r.cookie=e+"="+encodeURIComponent(a)+f+"; path=/"+c},remove:function(a,b){d.cookie.set(a,
"",-1,b)}};d.register_event=function(){function a(e,c,f){return function(a){if(a=a||b(window.event)){var g=!0,h;d.isFunction(f)&&(h=f(a));a=c.call(e,a);if(!1===h||!1===a)g=!1;return g}}}function b(a){a&&(a.preventDefault=b.preventDefault,a.stopPropagation=b.stopPropagation);return a}b.preventDefault=function(){this.returnValue=!1};b.stopPropagation=function(){this.cancelBubble=!0};return function(b,d,c,q){b?b.addEventListener&&!q?b.addEventListener(d,c,!1):(d="on"+d,b[d]=a(b,c,b[d])):v.error("No valid element provided to register_event")}}();
d.dom_query=function(){function a(e,d){return 0<=(" "+e.className+" ").replace(b," ").indexOf(" "+d+" ")}var b=/[\t\r\n]/g;return function(b){if(!r.getElementsByTagName)return[];b=b.split(" ");for(var c,q=Array(r),f=0;f<b.length;f++)if(c=b[f].replace(/^\s+/,"").replace(/\s+$/,""),-1<c.indexOf("#")){c=c.split("#");var g=c[0],q=r.getElementById(c[1]);if(!q||g&&q.nodeName.toLowerCase()!=g)return[];q=Array(q)}else if(-1<c.indexOf(".")){c=c.split(".");var g=c[0],h=c[1];g||(g="*");c=[];for(var k=0,p=0;p<
q.length;p++){var t;t="*"==g?q[p].all?q[p].all:q[p].getElementsByTagName("*"):q[p].getElementsByTagName(g);for(var l=0;l<t.length;l++)c[k++]=t[l]}q=[];for(k=g=0;k<c.length;k++)c[k].className&&(d.isString(c[k].className)&&a(c[k],h))&&(q[g++]=c[k])}else if(c.match(/^(\w*)\[(\w+)([=~\|\^\$\*]?)=?"?([^\]"]*)"?\]$/)){var g=RegExp.$1,n=RegExp.$2,h=RegExp.$3,u=RegExp.$4;g||(g="*");c=[];for(p=k=0;p<q.length;p++){t="*"==g?q[p].all?q[p].all:q[p].getElementsByTagName("*"):q[p].getElementsByTagName(g);for(l=
0;l<t.length;l++)c[k++]=t[l]}q=[];g=0;switch(h){case "=":h=function(a){return a.getAttribute(n)==u};break;case "~":h=function(a){return a.getAttribute(n).match(RegExp("\\b"+u+"\\b"))};break;case "|":h=function(a){return a.getAttribute(n).match(RegExp("^"+u+"-?"))};break;case "^":h=function(a){return 0==a.getAttribute(n).indexOf(u)};break;case "$":h=function(a){return a.getAttribute(n).lastIndexOf(u)==a.getAttribute(n).length-u.length};break;case "*":h=function(a){return-1<a.getAttribute(n).indexOf(u)};
break;default:h=function(a){return a.getAttribute(n)}}q=[];for(k=g=0;k<c.length;k++)h(c[k])&&(q[g++]=c[k])}else{g=c;c=[];for(p=k=0;p<q.length;p++){t=q[p].getElementsByTagName(g);for(l=0;l<t.length;l++)c[k++]=t[l]}q=c}return q}}();d.info={campaignParams:function(){var a="",b={};d.each(["utm_source","utm_medium","utm_campaign","utm_content","utm_term"],function(c){a=d.getQueryParam(r.URL,c);a.length&&(b[c]=a)});return b},searchEngine:function(a){return 0===a.search("https?://(.*)google.([^/?]*)")?"google":
0===a.search("https?://(.*)bing.com")?"bing":0===a.search("https?://(.*)yahoo.com")?"yahoo":0===a.search("https?://(.*)duckduckgo.com")?"duckduckgo":null},searchInfo:function(a){var b=d.info.searchEngine(a),c={};null!==b&&(c.g_search_engine=b,a=d.getQueryParam(a,"yahoo"!=b?"q":"p"),a.length&&(c.mp_keyword=a));return c},browser:function(){var a=x.vendor||"";return window.opera?d.includes(l,"Mini")?"Opera Mini":"Opera":/(BlackBerry|PlayBook|BB10)/i.test(l)?"BlackBerry":d.includes(l,"Chrome")?"Chrome":
d.includes(a,"Apple")?d.includes(l,"Mobile")?"Mobile Safari":"Safari":d.includes(l,"Android")?"Android Mobile":d.includes(l,"Konqueror")?"Konqueror":d.includes(l,"Firefox")?"Firefox":d.includes(l,"MSIE")?"Internet Explorer":d.includes(l,"Gecko")?"Mozilla":""},os:function(){return/Windows/i.test(l)?/Phone/.test(l)?"Windows Mobile":"Windows":/(iPhone|iPad|iPod)/.test(l)?"iOS":/Android/.test(l)?"Android":/(BlackBerry|PlayBook|BB10)/i.test(l)?"BlackBerry":/Mac/i.test(l)?"Mac OS X":/Linux/.test(l)?"Linux":
""},device:function(){return/iPhone/.test(l)?"iPhone":/iPad/.test(l)?"iPad":/iPod/.test(l)?"iPod Touch":/(BlackBerry|PlayBook|BB10)/i.test(l)?"BlackBerry":/Windows Phone/i.test(l)?"Windows Phone":/Android/.test(l)?"Android":""},referringDomain:function(a){a=a.split("/");return 3<=a.length?a[2]:""},properties:function(){return d.strip_empty_properties({os:d.info.os(),browser:d.info.browser(),device:d.info.device(),mp_lib:"web"})},people_properties:function(){return d.strip_empty_properties({$os:d.info.os(),
$browser:d.info.browser()})},pageviewInfo:function(a){return d.strip_empty_properties({mp_page:a,mp_referrer:r.referrer,mp_browser:d.info.browser(),mp_platform:d.info.os()})}};var v={log:function(){if(z&&!d.isUndefined(u)&&u)try{u.log.apply(u,arguments)}catch(a){d.each(arguments,function(a){u.log(a)})}},error:function(){if(z&&!d.isUndefined(u)&&u){var a=["Mixpanel error:"].concat(d.toArray(arguments));try{u.error.apply(u,a)}catch(b){d.each(a,function(a){u.error(a)})}}},critical:function(){if(!d.isUndefined(u)&&
u){var a=["Mixpanel error:"].concat(d.toArray(arguments));try{u.error.apply(u,a)}catch(b){d.each(a,function(a){u.error(a)})}}}},w=function(){};w.prototype.create_properties=function(){};w.prototype.event_handler=function(){};w.prototype.after_track_handler=function(){};w.prototype.init=function(a){this.mp=a;return this};w.prototype.track=function(a,b,c,f){var g=this,h=d.dom_query(a);if(0==h.length)v.error("The DOM query ("+a+") returned 0 elements");else return d.each(h,function(a){d.register_event(a,
this.override_event,function(a){var e={},d=g.create_properties(c,this),h=g.mp.get_config("track_links_timeout");g.event_handler(a,this,e);window.setTimeout(g.track_callback(f,d,e,!0),h);g.mp.track(b,d,g.track_callback(f,d,e))})},this),!0};w.prototype.track_callback=function(a,b,c,d){d=d||!1;var f=this;return function(){c.callback_fired||(c.callback_fired=!0,a&&!1===a(d,b)||f.after_track_handler(b,c,d))}};w.prototype.create_properties=function(a,b){return"function"===typeof a?a(b):d.extend({},a)};
var B=function(){this.override_event="click"};d.inherit(B,w);B.prototype.create_properties=function(a,b){var c=B.superclass.create_properties.apply(this,arguments);b.href&&(c.url=b.href);return c};B.prototype.event_handler=function(a,b,c){c.new_tab=2===a.which||a.metaKey||"_blank"===b.target;c.href=b.href;c.new_tab||a.preventDefault()};B.prototype.after_track_handler=function(a,b,c){b.new_tab||setTimeout(function(){window.location=b.href},0)};var E=function(){this.override_event="submit"};d.inherit(E,
w);E.prototype.event_handler=function(a,b,c){c.element=b;a.preventDefault()};E.prototype.after_track_handler=function(a,b,c){setTimeout(function(){b.element.submit()},0)};var n=function(a){this.props={};this.campaign_params_saved=!1;this.name=a.cookie_name?"mp_"+a.cookie_name:"mp_"+a.token+"_mixpanel";this.load();this.update_config(a);this.upgrade(a);this.save()};n.prototype.properties=function(){var a={};d.each(this.props,function(b,c){d.include(C,c)||(a[c]=b)});return a};n.prototype.load=function(){if(!this.disabled){var a=
d.cookie.parse(this.name);a&&(this.props=d.extend({},a))}};n.prototype.upgrade=function(a){var b=a.upgrade,c;b&&(c="mp_super_properties","string"===typeof b&&(c=b),b=d.cookie.parse(c),d.cookie.remove(c),d.cookie.remove(c,!0),b&&(this.props=d.extend(this.props,b.all,b.events)));if(!a.cookie_name&&"mixpanel"!==a.name&&(c="mp_"+a.token+"_"+a.name,b=d.cookie.parse(c)))d.cookie.remove(c),d.cookie.remove(c,!0),this.register_once(b)};n.prototype.save=function(){this.disabled||d.cookie.set(this.name,d.JSONEncode(this.props),
this.expire_days,this.cross_subdomain)};n.prototype.remove=function(){d.cookie.remove(this.name,!1);d.cookie.remove(this.name,!0)};n.prototype.clear=function(){this.remove();this.props={}};n.prototype.register_once=function(a,b,c){return d.isObject(a)?("undefined"===typeof b&&(b="None"),this.expire_days="undefined"===typeof c?this.default_expiry:c,d.each(a,function(a,e){if(!this.props[e]||this.props[e]===b)this.props[e]=a},this),this.save(),!0):!1};n.prototype.register=function(a,b){return d.isObject(a)?
(this.expire_days="undefined"===typeof b?this.default_expiry:b,d.extend(this.props,a),this.save(),!0):!1};n.prototype.unregister=function(a){a in this.props&&(delete this.props[a],this.save())};n.prototype.update_campaign_params=function(){this.campaign_params_saved||(this.register_once(d.info.campaignParams()),this.campaign_params_saved=!0)};n.prototype.update_search_keyword=function(a){this.register(d.info.searchInfo(a))};n.prototype.update_referrer_info=function(a){this.register_once({$initial_referrer:a||
"$direct",$initial_referring_domain:d.info.referringDomain(a)||"$direct"},"")};n.prototype.get_referrer_info=function(){return d.strip_empty_properties({$initial_referrer:this.props.$initial_referrer,$initial_referring_domain:this.props.$initial_referring_domain})};n.prototype.safe_merge=function(a){d.each(this.props,function(b,c){c in a||(a[c]=b)});return a};n.prototype.update_config=function(a){this.default_expiry=this.expire_days=a.cookie_expiration;this.set_disabled(a.disable_cookie);this.set_cross_subdomain(a.cross_subdomain_cookie)};
n.prototype.set_disabled=function(a){(this.disabled=a)&&this.remove()};n.prototype.set_cross_subdomain=function(a){a!==this.cross_subdomain&&(this.cross_subdomain=a,this.remove(),this.save())};n.prototype.get_cross_subdomain=function(){return this.cross_subdomain};n.prototype._add_to_people_queue=function(a,b){var c=this._get_queue_key(a),f=b[a],g=this._get_or_create_queue("$set"),h=this._get_or_create_queue("$add"),k=this._get_or_create_queue("$append",[]);"__mps"===c?(d.extend(g,f),this._pop_from_people_queue("$add",
f)):"__mpa"===c?d.each(f,function(a,e){e in g?g[e]+=a:(e in h||(h[e]=0),h[e]+=a)},this):"__mpap"===c&&k.push(f);v.log("MIXPANEL PEOPLE REQUEST (QUEUED, PENDING IDENTIFY):");v.log(b);this.save()};n.prototype._pop_from_people_queue=function(a,b){var c=this._get_queue(a);d.isUndefined(c)||(d.each(b,function(a,e){delete c[e]},this),this.save())};n.prototype._get_queue_key=function(a){if("$set"===a)return"__mps";if("$add"===a)return"__mpa";if("$append"===a)return"__mpap";v.error("Invalid queue:",a)};n.prototype._get_queue=
function(a){return this.props[this._get_queue_key(a)]};n.prototype._get_or_create_queue=function(a,b){var c=this._get_queue_key(a);b=d.isUndefined(b)?{}:b;return this.props[c]||(this.props[c]=b)};var F=function(e,b,c){var f,h="triggermail.lytics"===c?a:a[c];if(h&&!d.isArray(h))v.error("You have already initialized "+c);else return f=new g,f._init(e,b,c),f.people=new s,f.people._init(f),z=z||f.get_config("debug"),d.isUndefined(h)||(f._execute_array.call(f.people,h.people),f._execute_array(h)),f},g=
function(){};g.prototype.init=function(e,b,c){if("undefined"===typeof c)v.error("You must name your new library: init(token, config, name)");else if("triggermail.lytics"===c)v.error("You must initialize the main mixpanel object right after you include the Mixpanel js snippet");else return e=F(e,b,c),a[c]=e,e._loaded(),e};g.prototype._init=function(a,b,c){this.__loaded=!0;this.config={};this.set_config(d.extend({},M,b,{name:c,token:a,callback_fn:("triggermail.lytics"===c?c:"triggermail.lytics."+c)+
"._jsc"}));this._jsc=function(){};this.__dom_loaded_queue=[];this.__request_queue=[];this.__disabled_events=[];this._flags={disable_all_events:!1,identify_called:!1};this.cookie=new n(this.config);this.register_once({distinct_id:d.UUID()},"")};g.prototype._loaded=function(){this.get_config("loaded")(this);this.get_config("track_pageview")&&this.track_pageview()};g.prototype._dom_loaded=function(){d.each(this.__dom_loaded_queue,function(a){this._track_dom.apply(this,a)},this);d.each(this.__request_queue,
function(a){this._send_request.apply(this,a)},this);delete this.__dom_loaded_queue;delete this.__request_queue};g.prototype._track_dom=function(a,b){if(this.get_config("img"))return v.error("You can't use DOM tracking functions with img = true."),!1;if(!H)return this.__dom_loaded_queue.push([a,b]),!1;var c=(new a).init(this);return c.track.apply(c,b)};g.prototype._prepare_callback=function(a,b){if(d.isUndefined(a))return null;if(D)return function(c){a(c,b)};var c=this._jsc,f=""+Math.floor(1E8*Math.random()),
g=this.get_config("callback_fn")+'["'+f+'"]';c[f]=function(d){delete c[f];a(d,b)};return g};g.prototype._send_request=function(a,b,c){if(I)this.__request_queue.push(arguments);else{var f=this.get_config("verbose");this.get_config("test")&&(b.test=1);f&&(b.verbose=1);this.get_config("img")&&(b.img=1);c&&!D&&(b.callback=c);b.ip=this.get_config("ip")?1:0;b._=(new Date).getTime().toString();if("img"in b){var g=r.createElement("img");g.src=a;r.body.appendChild(g)}else if(D){var h=new XMLHttpRequest;h.open("POST",
a,!0);h.setRequestHeader("Content-Type","application/x-www-form-urlencoded");h.withCredentials=!0;h.onreadystatechange=function(a){4===h.readyState&&(200===h.status?c&&(f?c(d.JSONDecode(h.responseText)):c(Number(h.responseText))):(a="Bad HTTP status: "+h.status+" "+h.statusText,v.error(a),c&&(f?c({status:0,error:a}):c(0))))};h.send(d.HTTPBuildQuery(b))}else{a+="?"+d.HTTPBuildQuery(b);g=r.createElement("script");g.type="text/javascript";g.async=!0;g.defer=!0;g.src=a;var k=r.getElementsByTagName("script")[0];
k.parentNode.insertBefore(g,k)}}};g.prototype._execute_array=function(a){var b,c=[],f=[],g=[];d.each(a,function(a){a&&(b=a[0],"function"===typeof a?a.call(this):d.isArray(a)&&"alias"===b?c.push(a):d.isArray(a)&&-1!=b.indexOf("track")&&"function"===typeof this[b]?g.push(a):f.push(a))},this);a=function(a,b){d.each(a,function(a){this[a[0]].apply(this,a.slice(1))},b)};a(c,this);a(f,this);a(g,this)};g.prototype.push=function(a){this._execute_array([a])};g.prototype.disable=function(a){"undefined"===typeof a?
this._flags.disable_all_events=!0:this.__disabled_events=this.__disabled_events.concat(a)};g.prototype.track=function(a,b,c){if("undefined"===typeof a)v.error("No event name provided to mixpanel.track");else{b=b||{};b.token=b.token||this.get_config("token");this.cookie.update_search_keyword(r.referrer);this.get_config("store_google")&&this.cookie.update_campaign_params();this.get_config("save_referrer")&&this.cookie.update_referrer_info(r.referrer);b=d.extend({},d.info.properties(),this.cookie.properties(),
b);delete b.ch;b={event:a,properties:b};z&&(b.validate=1);b=d.truncate(b,1023);var f=d.JSONEncode(b),f=d.base64Encode(f);v.log("MIXPANEL REQUEST:");v.log(b);payload={data:f};-1!=this.get_distinct_id().indexOf("live_demo")?(payload.live_demo=!0,this._send_request(this.get_config("api_host")+"/templates/demo_track/"+a,payload,this._prepare_callback(c,b))):this._send_request(this.get_config("api_host")+"/track/"+a,payload,this._prepare_callback(c,b));return b}};g.prototype.track_pageview=function(a){"undefined"===
typeof a&&(a=r.location.href);this.track("mp_page_view",d.info.pageviewInfo(a))};g.prototype.track_links=function(){return this._track_dom.call(this,B,arguments)};g.prototype.track_forms=function(){return this._track_dom.call(this,E,arguments)};g.prototype.register=function(a,b){this.cookie.register(a,b)};g.prototype.register_once=function(a,b,c){this.cookie.register_once(a,b,c)};g.prototype.unregister=function(a){this.cookie.unregister(a)};g.prototype._register_single=function(a,b){var c={};c[a]=
b;this.register(c)};g.prototype.identify=function(a,b,c,d){a!=this.get_distinct_id()&&a!=this.get_property("__alias")&&(this.unregister("__alias"),this._register_single("distinct_id",a));this._flags.identify_called=!0;this.people._flush(b,c,d)};g.prototype.get_distinct_id=function(){return this.get_property("distinct_id")};g.prototype.alias=function(a,b){if(a===this.get_property("$people_distinct_id"))return v.critical("Attempting to create alias for existing People user - aborting."),-2;var c=this;
d.isUndefined(b)&&(b=this.get_distinct_id());if(a!==b)return this._register_single("__alias",a),this.track("$create_alias",{alias:a,distinct_id:b},function(b){c.identify(a)});v.error("alias matches current distinct_id - skipping api call.");this.identify(a);return-1};g.prototype.name_tag=function(a){this._register_single("mp_name_tag",a)};g.prototype.set_config=function(a){d.isObject(a)&&(d.extend(this.config,a),this.cookie&&this.cookie.update_config(this.config),z=z||this.get_config("debug"))};g.prototype.get_config=
function(a){return this.config[a]};g.prototype.get_property=function(a){return this.cookie.props[a]};g.prototype.toString=function(){var a=this.get_config("name");"triggermail.lytics"!==a&&(a="triggermail.lytics."+a);return a};var s=function(){};s.prototype._init=function(a){this._mixpanel=a};s.prototype.set=function(a,b,c){var f={},g={};d.isObject(a)?(d.each(a,function(a,b){"$distinct_id"==b||"$token"==b||(g[b]=a)}),c=b):g[a]=b;this._get_config("save_referrer")&&this._mixpanel.cookie.update_referrer_info(r.referrer);
g=d.extend({},d.info.people_properties(),this._mixpanel.cookie.get_referrer_info(),g);f.$set=g;return this._send_request(f,c)};s.prototype.increment=function(a,b,c){var f={},g={};d.isObject(a)?(d.each(a,function(a,b){"$distinct_id"==b||"$token"==b||(isNaN(parseFloat(a))?v.error("Invalid increment value passed to mixpanel.people.increment - must be a number"):g[b]=a)}),c=b):(d.isUndefined(b)&&(b=1),g[a]=b);f.$add=g;return this._send_request(f,c)};s.prototype.append=function(a,b,c){var f={},g={};d.isObject(a)?
(d.each(a,function(a,b){"$distinct_id"==b||"$token"==b||(g[b]=a)}),c=b):g[a]=b;f.$append=g;return this._send_request(f,c)};s.prototype.track_charge=function(a,b,c){if(!d.isNumber(a)&&(a=parseFloat(a),isNaN(a))){v.error("Invalid value passed to mixpanel.people.track_charge - must be a number");return}return this.append("$transactions",d.extend({$amount:a},b),c)};s.prototype.clear_charges=function(a){return this.set("$transactions",[],a)};s.prototype.delete_user=function(){if(this._identify_called()){var a=
{$delete:this._mixpanel.get_distinct_id()};return this._send_request(a)}v.error("mixpanel.people.delete_user() requires you to call identify() first")};s.prototype.toString=function(){return this._mixpanel.toString()+".people"};s.prototype._send_request=function(a,b){a.$token=this._get_config("token");a.$distinct_id=this._mixpanel.get_distinct_id();var c=d.encodeDates(a),f=d.truncate(c,255),c=d.JSONEncode(c),c=d.base64Encode(c);if(!this._identify_called())return this._enqueue(a),d.isUndefined(b)||
(this._get_config("verbose")?b({status:-1,error:null}):b(-1)),f;v.log("MIXPANEL PEOPLE REQUEST:");v.log(f);this._mixpanel._send_request(this._get_config("api_host")+"/engage/",{data:c},this._mixpanel._prepare_callback(b,f));return f};s.prototype._get_config=function(a){return this._mixpanel.get_config(a)};s.prototype._identify_called=function(){return!0===this._mixpanel._flags.identify_called};s.prototype._enqueue=function(a){"$set"in a?this._mixpanel.cookie._add_to_people_queue("$set",a):"$add"in
a?this._mixpanel.cookie._add_to_people_queue("$add",a):"$append"in a?this._mixpanel.cookie._add_to_people_queue("$append",a):v.error("Invalid call to _enqueue():",a)};s.prototype._flush=function(a,b,c){var f=this,g=d.extend({},this._mixpanel.cookie._get_queue("$set")),h=d.extend({},this._mixpanel.cookie._get_queue("$add")),k=this._mixpanel.cookie._get_queue("$append");!d.isUndefined(g)&&(d.isObject(g)&&!d.isEmptyObject(g))&&(f._mixpanel.cookie._pop_from_people_queue("$set",g),this.set(g,function(b,
c){0==b&&f._mixpanel.cookie._add_to_people_queue("$set",g);d.isUndefined(a)||a(b,c)}));!d.isUndefined(h)&&(d.isObject(h)&&!d.isEmptyObject(h))&&(f._mixpanel.cookie._pop_from_people_queue("$add",h),this.increment(h,function(a,c){0==a&&f._mixpanel.cookie._add_to_people_queue("$add",h);d.isUndefined(b)||b(a,c)}));if(!d.isUndefined(k)&&d.isArray(k)&&k.length)for(var p=k.length-1;0<=p;p--){var l=k.pop();f.append(l,function(a,b){0==a&&f._mixpanel.cookie._add_to_people_queue("$append",l);d.isUndefined(c)||
c(a,b)})}};d.toArray=d.toArray;d.isObject=d.isObject;d.JSONEncode=d.JSONEncode;d.JSONDecode=d.JSONDecode;d.isEmptyObject=d.isEmptyObject;g.prototype.init=g.prototype.init;g.prototype.disable=g.prototype.disable;g.prototype.track=g.prototype.track;g.prototype.track_links=g.prototype.track_links;g.prototype.track_forms=g.prototype.track_forms;g.prototype.track_pageview=g.prototype.track_pageview;g.prototype.register=g.prototype.register;g.prototype.register_once=g.prototype.register_once;g.prototype.unregister=
g.prototype.unregister;g.prototype.identify=g.prototype.identify;g.prototype.alias=g.prototype.alias;g.prototype.name_tag=g.prototype.name_tag;g.prototype.set_config=g.prototype.set_config;g.prototype.get_config=g.prototype.get_config;g.prototype.get_property=g.prototype.get_property;g.prototype.get_distinct_id=g.prototype.get_distinct_id;g.prototype.toString=g.prototype.toString;n.prototype.properties=n.prototype.properties;n.prototype.update_search_keyword=n.prototype.update_search_keyword;n.prototype.update_referrer_info=
n.prototype.update_referrer_info;n.prototype.get_cross_subdomain=n.prototype.get_cross_subdomain;n.prototype.clear=n.prototype.clear;s.prototype.set=s.prototype.set;s.prototype.increment=s.prototype.increment;s.prototype.append=s.prototype.append;s.prototype.track_charge=s.prototype.track_charge;s.prototype.clear_charges=s.prototype.clear_charges;s.prototype.delete_user=s.prototype.delete_user;s.prototype.toString=s.prototype.toString;if(d.isUndefined(a))v.critical("'mixpanel' object not initialized. Ensure you are using the latest version of the Mixpanel JS Library along with the snippet we provide.");
else if(a.__loaded||a.config&&a.cookie)v.error("Mixpanel library has already been downloaded at least once.");else if(1.1>f)v.critical("Version mismatch; please ensure you're using the latest version of the Mixpanel code snippet.");else{var y={};d.each(a._i,function(a){var b;a&&d.isArray(a)&&(b=a[a.length-1],a=F.apply(this,a),y[b]=a)});var N=function(){d.each(y,function(b,c){"triggermail.lytics"!==c&&(a[c]=b)});a._=d};a.init=function(b,c,d){d?a[d]||(a[d]=y[d]=F(b,c,d),a[d]._loaded()):(d=a,y["triggermail.lytics"]?
d=y["triggermail.lytics"]:b&&(d=F(b,c,"triggermail.lytics")),window["triggermail.lytics"]=a=d,N())};a.init();d.each(y,function(a){a._loaded()});if(r.addEventListener)"complete"==r.readyState?b():r.addEventListener("DOMContentLoaded",b,!1);else if(r.attachEvent){r.attachEvent("onreadystatechange",b);f=!1;try{f=null==window.frameElement}catch(O){}if(r.documentElement.doScroll&&f){var J=function(){try{r.documentElement.doScroll("left")}catch(a){setTimeout(J,1);return}b()};J()}}d.register_event(window,
"load",b,!0)}})(window.triggermail.lytics);
jQuery.extend(triggermail,function(){var a=function(a){var c=triggermail.lytics.get_property("ch"),f=triggermail.util.hashCode(JSON.stringify(a));f!=c&&(triggermail.lytics.register({ch:f.toString()},365),triggermail.track("identify",{customer:a}));return a};return{track:function(a,c){var f=triggermail.lytics.cookie.props;f.distinct_id&&jQuery.extend(c,{distinct_id:f.distinct_id});delete c.ch;try{c.url=window.location.href,-1<c.url.indexOf("s.thebrighttag")&&delete c.url}catch(h){}"page_view"!=a&&
("true"==triggermail.util.cookie.get("tm_debug")?triggermail.lytics.track(a,c,this.track_callback(a,c)):triggermail.lytics.track(a,c));triggermail.lytics.get_distinct_id()&&(c.distinct_id=triggermail.lytics.get_distinct_id());try{!0===triggermail.integ.debug&&console.debug(a,c)}catch(k){}},report_to_insanetiego:function(a,c){if("true"===triggermail.util.cookie.get("tm_debug")){0===$("#insanetiego").length&&triggermail.insanetiego.inject_div();var f=prettyPrint(c,{styles:{array:{th:{display:"none"}},
object:{th:{display:"none"}},"default":{th:{display:"none"}}}});$("#insanetiego").append("<p><b>Event: "+a+"</b></p>");$("#insanetiego").append(f);$.each(c.products,function(a,b){var c,f;b.image&&$("<img/>").attr("src",b.image).load(function(){c=this.width;f=this.height;$("#insanetiego").append("<p><b>Image size: width-"+c+" height-"+f+"<b></p>");$("#insanetiego").append('<img src="'+b.image+'" height="100" width="100" />')});b.alternative_image&&(c=this.width,f=this.height,$("<img/>").attr("src",
b.alternative_image).load(function(){c=this.width;f=this.height;$("#insanetiego").append("<p><b>Alternative Image size: width-"+c+" height-"+f+"<b></p>");$("#insanetiego").append('<img src="'+b.alternative_image+'" height="100" width="100"/>')}))})}},validate:function(a){"true"===triggermail.util.cookie.get("tm_debug")&&(a?$("#insanetiego").append('<p><b style="color:#64E813;">Event is ok</b></p>'):$("#insanetiego").append('<p><b style="color:#E60508;">The Event Seems Broken</b></p>'))},track_callback:function(a,
c){return function(f){triggermail.report_to_insanetiego(a,c);triggermail.validate(f)}},add_to_cart:function(a){return this.track("add_to_cart",{products:[a]})},remove_from_cart:function(a){return this.track("remove_from_cart",{products:[a]})},wishlist:function(a){return this.track("wishlist",{products:[a]})},view_cart:function(a){return this.track("viewed_cart",a)},stop:function(a){return this.track("stop",a)},page:function(a){return this.track("page_view",a)},purchase:function(a){return this.track("purchase",
a)},checkout_start:function(a){return this.track("checkout_start",a)},view:function(a,c){triggermail.integ.salt_products&&(a.salt=Math.random().toString(36).replace(".",""));var f=jQuery.extend(c||{},{products:[a]});return this.track("viewed_product",f)},view_content:function(a,c){triggermail.integ.salt_products&&(a.salt=Math.random().toString(36).replace(".",""));var f=jQuery.extend(c||{},{contents:[a]});return this.track("viewed_content",f)},search:function(a){return this.track("search",a)},identify:function(b){return a(b)},
subscribe:function(b){b.source="newsletter";return a(b)},unsubscribe:function(a){return this.track("unsubscribe",a)},patch:function(a){return this.track("patch",a)},merge:function(a){return this.track("merge",a)},init:function(a){},exception:function(a){var c={};jQuery.extend(c,triggermail.lytics._.info.properties());try{c.url=window.location.href,-1<c.url.indexOf("s.thebrighttag")&&delete c.url,c.message=a.message}catch(f){}c.error=a;this.track("exception",c)},EMAIL_ADDRESS_PROPERTY:"email_address",
PAGE_VIEW:"page_view",MAX_PROPERTY_LENGTH:1024}}());
triggermail.util=function(){return{price:function(a){return isNaN(parseFloat(a))?parseFloat(a.replace(/[^0-9\.]/g,"")):parseFloat(a)},unique:function(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return jQuery.map(b,function(a,c){return c})},slugify:function(a){return a.toLowerCase().replace(/[^\w ]+/g,"").replace(/ +/g,"-")},serializeForm:function(a){var b={};a=a.serializeArray();$.each(a,function(){void 0!==b[this.name]?(b[this.name].push||(b[this.name]=[b[this.name]]),b[this.name].push(this.value||
"")):b[this.name]=this.value||""});return b},getUrlParam:function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?&]"+a+"=([^&#]*)").exec(window.location.search);return null==a?"":decodeURIComponent(a[1].replace(/\+/g," "))},isMobile:function(){var a=!1,b="iphone;ipad;android;blackberry;nokia;opera mini;windows mobile;windows phone;iemobile".split(";"),c;for(c in b)0<navigator.userAgent.toLowerCase().indexOf(b[c].toLowerCase())&&(a=!0);return a},getParamFromQueryString:function(a,
b){return decodeURI((RegExp(b+"=(.+?)(&|$)").exec(a)||[,null])[1])},trimString:function(a,b){return jQuery.trim(a).substring(0,b)},isAnonymousUser:function(){var a=triggermail.lytics.get_property(triggermail.core.EMAIL_ADDRESS_PROPERTY);return!this.isValidEmail(a)},emRegex:/\S+@\S+\.\S+/,isValidEmail:function(a){return triggermail.util.emRegex.test(a)},findEmail:function(a,b){try{return"undefined"==typeof b&&(b=triggermail.util.emRegex),b.exec(a).pop()}catch(c){}},hashCode:function(a){var b=0,c,f;
if(0==a.length)return b;for(c=0;c<a.length;c++)f=a.charCodeAt(c),b=(b<<5)-b+f,b&=b;return b},productHash:function(a){a=this.sanitizeProductName(a[TriggerMail.PRODUCT_NAME_PROPERTY]);return this.hashCode(a)},_getbyte64:function(a,b){_ALPHA="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";var c=_ALPHA.indexOf(a.charAt(b));if(-1===c)throw"Cannot decode base64";return c},b64decode:function(a){var b=0,c,f,h=a.length,k=[];a=String(a);if(0===h)return a;if(0!==h%4)throw"Cannot decode base64";
"="===a.charAt(h-1)&&(b=1,"="===a.charAt(h-2)&&(b=2),h-=4);for(c=0;c<h;c+=4)f=this._getbyte64(a,c)<<18|this._getbyte64(a,c+1)<<12|this._getbyte64(a,c+2)<<6|this._getbyte64(a,c+3),k.push(String.fromCharCode(f>>16,f>>8&255,f&255));switch(b){case 1:f=this._getbyte64(a,c)<<18|this._getbyte64(a,c+1)<<12|this._getbyte64(a,c+2)<<6;k.push(String.fromCharCode(f>>16,f>>8&255));break;case 2:f=this._getbyte64(a,c)<<18|this._getbyte64(a,c+1)<<12,k.push(String.fromCharCode(f>>16))}return k.join("")},wrapEvent:function(a){var b=
Array.prototype.slice.call(arguments,1);return function(){try{return a.apply(this,b.concat(Array.prototype.slice.call(arguments,0)))}catch(c){}}},removeURLParam:function(a,b){return triggermail.util.updateURLParams(a,b,!1)},keepURLParam:function(a,b){return triggermail.util.updateURLParams(a,b,!0)},updateURLParams:function(a,b,c){var f=a.split("?")[0],h=[],h=-1!==a.indexOf("?")?a.split("?")[1]:"";if(""!==h){for(var h=h.split("&"),k=h.length-1;0<=k;k-=1)a=h[k].split("=")[0],c?jQuery.isArray(b)?-1==
b.indexOf(a)&&h.splice(k,1):a!=b&&h.splice(k,1):jQuery.isArray(b)?-1<b.indexOf(a)&&h.splice(k,1):a==b&&h.splice(k,1);f+=0<h.length?"?"+h.join("&"):""}return f},getArrayElementFromQueryString:function(a,b){var c=[];a||(a=location.href);b=b.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");for(var f=RegExp(b+"=([^&#]+)","ig");;){var h=f.exec(a);if(h&&h[1])c.push(h[1]);else break}return c.length?1==c.length?c[0]:c:null}}}();triggermail.util.cookie=triggermail.lytics._.cookie;triggermail.util.encode=triggermail.lytics._.JSONEncode;
triggermail.util.decode=triggermail.lytics._.JSONDecode;triggermail.demo=function(){var a=triggermail.lytics.get_distinct_id();-1==a.indexOf("live_demo")&&(triggermail.lytics._register_single("distinct_id","live_demo_"+a),a=triggermail.lytics.get_distinct_id());triggermail.lytics.cookie.update_config({live_demo:!0,cookie_expiration:1});window.open("http://www.bluecore.com/api/templates/live_demo/"+triggermail.Partner.keys.lytics.p+"/"+a)};
triggermail.util.walk=function(a,b){b(a);for(a=a.firstChild;a;)walk(a,b),a=a.nextSibling};triggermail.util.walkUntil=function(a,b,c){ret=b(a);if(!0===c(ret))return ret;for(a=a.firstChild;a;)walk(a,b),a=a.nextSibling};
triggermail.insanetiego=function(){return{inject_div:function(){$("body").append('<div id="insanetiego" style="position:fixed;bottom:0;width:100%;background:#D8E7ED;height:300px;overflow:scroll;z-index:2000;border-top-style:solid;border-top-width:5px;"></div>')},remove_div:function(){$("#insanetiego").remove()},debug:function(){triggermail.util.cookie.set("tm_debug",!0);triggermail.integ.debug=!0;this.inject_div()},undebug:function(){triggermail.util.cookie.set("tm_debug",!1);triggermail.integ.debug=
!1}}}();triggermail.core={};triggermail.core.sanitizer=function(){return{sanitize:function(a,b){if("email"==a){var c;c=/\S+@\S+\.\S+/.test(b)?b:null;return c}return b?b:""}}}();
triggermail.integ=function(){return{init:function(){"undefined"!=typeof triggermail.Partner.init?triggermail.Partner.init():triggermail.integ.partnerInit();try{triggermail.integ.checkLoop()}catch(a){}},partnerInit:function(){var a=triggermail.Partner;if(!jQuery(".translated-rtl, .translated-rtl").length&&!jQuery('meta[http-equiv="X-Translated-By"]').length){try{a.trackProductView()}catch(b){triggermail.exception(b)}try{triggermail.Partner.trackAddToCart()}catch(c){triggermail.exception(c)}try{triggermail.Partner.trackCheckoutStart()}catch(f){triggermail.exception(f)}try{triggermail.Partner.trackCheckout()}catch(h){triggermail.exception(h)}try{triggermail.Partner.watchEmail()}catch(k){triggermail.exception(k)}if(triggermail.Partner.hasOwnProperty("trackRemoveFromCart"))try{triggermail.Partner.trackRemoveFromCart()}catch(p){triggermail.exception(p)}if(triggermail.Partner.hasOwnProperty("trackUnsubscribe"))try{triggermail.Partner.trackUnsubscribe()}catch(u){triggermail.exception(u)}if(triggermail.Partner.hasOwnProperty("trackSubscribe"))try{triggermail.Partner.trackSubscribe()}catch(x){triggermail.exception(x)}if(triggermail.Partner.hasOwnProperty("trackSearch"))try{triggermail.Partner.trackSearch()}catch(r){triggermail.exception(r)}if(triggermail.Partner.hasOwnProperty("trackWishlist"))try{triggermail.Partner.trackWishlist()}catch(l){triggermail.exception(l)}if(triggermail.Partner.hasOwnProperty("trackContentView"))try{triggermail.Partner.trackContentView()}catch(C){triggermail.exception(C)}}},checkLoop:function(){for(var a=
"email kmi utm_email tmemail tme e user_email_address".split(" "),b=0;b<a.length;b++){var c=triggermail.util.getUrlParam(a[b]);if(triggermail.util.isValidEmail(c)){triggermail.identify({email:c});return}}a=triggermail.util.getUrlParam("obem");"undefined"!=typeof a&&""!=a&&triggermail.identify({obem:a})}}}();
triggermail.integ.ProductFetcher=__tmClass.extend({name:function(){return this._name},readOg:function(a){return jQuery('meta[property="'+a+'"]').attr("content")},category:function(){return this._category},color:function(){return this._color},size:function(){return this._size},price:function(){return this._price},brand:function(){return this._brand},id:function(){return this._id},image:function(){return this._image},url:function(){return this._url},out_of_stock:function(){return!1},tags:function(){return this._tags},
to_dict:function(){try{var a={name:triggermail.core.sanitizer.sanitize("name",this.name()),category:triggermail.core.sanitizer.sanitize("category",this.category()),size:triggermail.core.sanitizer.sanitize("size",this.size()),price:triggermail.core.sanitizer.sanitize("price",this.price()),brand:triggermail.core.sanitizer.sanitize("brand",this.brand()),id:triggermail.core.sanitizer.sanitize("id",this.id()),image:triggermail.core.sanitizer.sanitize("image",this.image()),url:triggermail.core.sanitizer.sanitize("url",
this.url()),out_of_stock:this.out_of_stock(),tags:this.tags(),color:triggermail.core.sanitizer.sanitize("color",this.color())},b;for(b in a)(""===a[b]||!1==a[b]&&"out_of_stock"!=b)&&delete a[b];jQuery.extend(a,this.extra_props());jQuery.extend(a,this.heat_level());return a}catch(c){triggermail.exception({location:"product_fetcher",error:c})}},extra_props:function(){return{}},fetch:function(){return this.to_dict()},related_products_raw:function(){return this._related_products},heat_level:function(){return this._heat_level}});
triggermail.integ.ContentFetcher=__tmClass.extend({name:function(){return this._name},id:function(){return this._id},image:function(){return this._image},url:function(){return this._url},title:function(){return this._title},to_dict:function(){try{var a={id:triggermail.core.sanitizer.sanitize("id",this.id()),image:triggermail.core.sanitizer.sanitize("image",this.image()),name:triggermail.core.sanitizer.sanitize("name",this.name()),title:triggermail.core.sanitizer.sanitize("title",this.title()),url:triggermail.core.sanitizer.sanitize("url",
this.url())},b;for(b in a)(""===a[b]||!1==a[b])&&delete a[b];jQuery.extend(a,this.extra_props());return a}catch(c){triggermail.exception({location:"content_fetcher",error:c})}},extra_props:function(){return{}},fetch:function(){return this.to_dict()}});triggermail.integ.initServices=function(){triggermail.lytics.init(triggermail.integ.keys.lytics);triggermail.lytics=window["triggermail.lytics"];triggermail.lytics.set_config({save_referrer:!1,store_google:!1,debug:triggermail.integ.debug})};
triggermail.integ.loadJQuery=function(){var a=document.createElement("script");a.type="text/javascript";a.src=("https:"===document.location.protocol?"https://":"http://")+"ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)};
triggermail.fetcher=triggermail.integ.ProductFetcher.extend({name:function(){return triggermail.productData.productTitle},category:function(){return triggermail.productData.trackingData.product.category.toLowerCase()},id:function(){return triggermail.productData.productId},brand:function(){},image:function(){var a=$('meta[property="og:image"]').attr("content"),a=""!=triggermail.util.getParamFromQueryString(a,"hei")?a.replace(/hei=\d+/,"hei=150"):a+"&hei=150";return a=""!=triggermail.util.getParamFromQueryString(a,
"wid")?a.replace(/wid=\d+/,"wid=150"):a+"&wid=150"},price:function(){return triggermail.util.price(triggermail.productData.localPrice)},out_of_stock:function(){return!triggermail.productData.inStock?!0:!1},url:function(){return window.location.href.split("?")[0].replace("http://m.nike.com/","http://store.nike.com/")},extra_props:function(){var a={is_nike_id:"false"};if(triggermail.productData.reviews.averageRating){var b=Math.round(100*triggermail.productData.reviews.averageRating)/100;a.rating=b}triggermail.productData.overriddenLocalPrice&&
(a.original_price=triggermail.util.price(triggermail.productData.overriddenLocalPrice),a.on_sale=!0);triggermail.productData.featuredTechnology&&$.each(triggermail.productData.featuredTechnology,function(c,b){a["featured_technology_"+c.toString()]=b.title});if(null!=triggermail.productData.productSubTitle){a.subtitle=triggermail.productData.productSubTitle;switch(triggermail.productData.trackingData.product.gender){case "1":a.gender="mens";break;case "2":a.gender="womens";break;case "3":-1<triggermail.productData.productSubTitle.toLowerCase().indexOf("toddler")?
a.gender="infant":a.gender="boys";break;case "4":-1<triggermail.productData.productSubTitle.toLowerCase().indexOf("toddler")?a.gender="infant":a.gender="girls"}a.subcategory=triggermail.productData.productSubTitle.toLowerCase().split(" ").pop()}a.primary_sport_raw=triggermail.fetcher.get_primary_sport_raw(!1);a.primary_sport=triggermail.fetcher.get_primary_sport(!1);"NFL"===a.primary_sport&&("undefined"!=typeof $(".exp-pdp-nfl-team-breadcrumb").attr("data-teamname")?a.team_name=$(".exp-pdp-nfl-team-breadcrumb").attr("data-teamname").toLowerCase():
a.team_name=$('[data-gadget="nike.gadget.CrossSell"]').attr("data-nfl-team-name").toLowerCase());"undefined"==typeof a.gender&&(a.gender="unisex");a.style_id=triggermail.productData.styleNumber;a.has_style_id=!0;-1<triggermail.productData.productTitle.toLowerCase().indexOf("jordan")&&(a.is_jordan="true",a.primary_sport="jordan");-1<triggermail.productData.productTitle.toLowerCase().indexOf("hurley")&&(a.is_hurley="true",a.primary_sport="hurley");-1<triggermail.productData.productTitle.toLowerCase().indexOf("nike+")&&
(a.is_nike_plus="true");return a}});
triggermail.NikeContentFetcher=triggermail.integ.ContentFetcher.extend({id:function(){try{return JSON.parse($(".trackingData")[0].innerHTML).response.contentPath.join("/")}catch(a){}},image:function(){try{return $(".nike-cq-fst-background-image img")[0].src}catch(a){}},name:function(){try{return $(".nike-cq-nav-title-wrapped")[0].innerHTML.toLowerCase()}catch(a){}},url:function(){return window.location.href.split("?")[0]},title:function(){try{var a="";if("nfl"==$(".nike-cq-nav-title-wrapped").text().toLowerCase())return $(".nike-cq-title-headline span").first().text();
1<$(".nike-cq-fst-carousel .nike-cq-carousel-slide").length?$(".nike-cq-fst-carousel .nike-cq-carousel-slide[data-slide-index='2'] .nike-cq-title-headline span.nike-cq-font50px").each(function(){a+=$(this).text()+" "}):$(".nike-cq-title-headline span.nike-cq-font50px").each(function(){a+=$(this).text()+" "});return a.trim()}catch(b){}},extra_props:function(){try{var a={},b=JSON.parse($(".trackingData")[0].innerHTML);a.headline=this.title();a.primary_sport="nfl"==b.response.sportCategory?"NFL":b.response.sportCategory;
"nfl"==$(".nike-cq-nav-title-wrapped").text().toLowerCase()?a.subtitle=$(".nike-cq-title-headline span")[1].innerHTML:a.subtitle=$(".nike-cq-block-subtitle").text().trim();a.team_name=0<$(".nike-cq-nav-title-wrapped").length?$(".nike-cq-nav-title-wrapped")[0].innerHTML.toLowerCase():"";$(".nike-cq-portrait-merch-zone-v2 .nike-cq-carousel .nike-cq-carousel-slide").each(function(c,b){a["top_product_name_"+c.toString()]=$(b).find("a").attr("data-tracking");a["top_product_url_"+c.toString()]=$(b).find("a").attr("href");
a["top_product_image_"+c.toString()]=$(b).find("img").attr("src")});$(".nike-cq-block-cta-pair a:visible").each(function(c,b){a["cta_"+c.toString()]=$(b).attr("data-tracking");a["cta_link_"+c.toString()]=$(b).attr("href")});0<$(".nike-cq-p2-touts-wrapper .nike-cq-pes-reference").length&&$(".nike-cq-p2-touts-wrapper .nike-cq-pes-reference").each(function(c,b){2>c&&(a["boxzone_image_"+c.toString()]=$(b).find("img").attr("src"),a["boxzone_link_"+c.toString()]=$(b).find("a").attr("href"),a["boxzone_headline_"+
c.toString()]=$(b).find(".nike-cq-subtitle-styled-header").text())});0<$(".nike-cq-editorial-grid-grid li").length&&$(".nike-cq-editorial-grid-grid li").each(function(c,b){a["boxzone_image_"+c.toString()]=$(b).find("img").attr("src");a["boxzone_link_"+c.toString()]=$(b).find("a").attr("href");a["boxzone_headline_"+c.toString()]=$(b).find(".nike-cq-subtitle-styled-header").text()});a.has_boxzones="undefined"!=typeof a.boxzone_image_0?"true":"false";return a}catch(c){}}});
triggermail.Partner=function(){return{trackProductView:function(){try{triggermail.Partner.commonProductView()}catch(a){}},trackContentView:function(){var a=Math.floor(100*Math.random());if(-1<window.location.href.indexOf("/c/nfl")&&25>a){var b=new triggermail.NikeContentFetcher;""!=b.name()&&void 0!=b.name()&&triggermail.view_content(b.to_dict())}if(-1<window.location.href.indexOf("m.nike.com/us/en_us/c/basketball")&&25>a){var a=window.location.href.split(/[#?]/)[0].split("/").pop(),c={id:triggermail.util.slugify(a),
name:triggermail.util.slugify(a),image:"http://www.triggermail.io/images/blue_logo.png",url:"www.nike.com"+window.location.pathname,primary_image:$(".nike-cq-fst-background-image img").eq(0).attr("src"),headline:jQuery(".nike-cq-title-headline .nike-cq-title-line").first().text().replace(/\s\s+/g," ")};try{var f=jQuery(".nike-cq-title-headline .nike-cq-title-line").eq(1).html().split("<br>");jQuery(f).each(function(a,b){c["subhead_"+a.toString()]=b.trim()});for(var h=f.length;3>h;h++)c["subhead_"+
h]=""}catch(k){}var p=jQuery(".nike-cq-fst-component").length;jQuery(".nike-cq-fst-component").each(function(a,b){if(1==a)try{c.primary_boxzone_0_image=jQuery(b).find("img").eq(0).attr("src"),0<jQuery(b).find("a").length?c.primary_boxzone_0_link=jQuery(b).find("a").eq(0).attr("href"):c.primary_boxzone_0_link=window.location.href.split(/[#?]/)[0],c.primary_boxzone_0_headline=jQuery(b).find(".nike-cq-title-line-1").text().trim().replace(/\s\s+/g," "),c.primary_boxzone_0_subhead=jQuery(b).find(".nike-cq-title-line-2").text().trim().replace(/\s\s+/g,
" ")}catch(f){}if(3<p&&a==p-2)try{c.secondary_boxzone_1_image=jQuery(b).find("img").eq(0).attr("src"),0<jQuery(b).find("a").length?c.secondary_boxzone_1_link=jQuery(b).find("a").eq(0).attr("href"):c.secondary_boxzone_1_link=window.location.href.split(/[#?]/)[0],c.secondary_boxzone_1_link=jQuery(b).find("a").eq(0).attr("href"),c.secondary_boxzone_1_headline=jQuery(b).find(".nike-cq-title-line-1").text().trim().replace(/\s\s+/g," "),c.secondary_boxzone_1_subhead=jQuery(b).find(".nike-cq-title-line-2").text().trim().replace(/\s\s+/g,
" ")}catch(h){}if(3<p&&a==p-1)try{c.secondary_boxzone_2_image=jQuery(b).find("img").eq(0).attr("src"),0<jQuery(b).find("a").length?c.secondary_boxzone_2_link=jQuery(b).find("a").eq(0).attr("href"):c.secondary_boxzone_2_link=window.location.href.split(/[#?]/)[0],c.secondary_boxzone_2_headline=jQuery(b).find(".nike-cq-title-line-1").text().trim().replace(/\s\s+/g," "),c.secondary_boxzone_2_subhead=jQuery(b).find(".nike-cq-title-line-2").text().trim().replace(/\s\s+/g," ")}catch(k){}});try{triggermail.view_content(c)}catch(u){}}try{if("launch_calendar_story"==
nike.analytics.currentPageId){tags_array=[];jQuery(".nike-cq-product-launch-body-sidebar-tagcloud ul a").each(function(a,b){tags_array.push(jQuery(b).text())});var x={};jQuery(".nike-cq-product-launch-body-main img").each(function(a,b){x["image_"+a.toString()]=b.src});var r=new Date,l=new Date(jQuery(".nike-cq-launch-date-uppercase").text().replace(",","")),c={id:jQuery('meta[property="og:url"]').attr("content").split("/").pop(),url:jQuery('meta[property="og:url"]').attr("content"),image:jQuery(".nike-cq-product-launch-hero-image img")[0].src,
thumbnail_image:jQuery('meta[property="og:image"]').attr("content"),name:jQuery(".nike-cq-product-launch-body-section-container .nike-cq-subtitle-headline").text(),launch_date:jQuery(".nike-cq-launch-date-uppercase").text(),price:triggermail.util.price(jQuery(".nike-cq-launch-price").text()),tags:tags_array.join(","),has_launched:l<r,is_launch:!0};jQuery.extend(c,x);triggermail.view_content(c)}}catch(C){}},trackAddToCart:function(){try{triggermail.Partner.doTrackAddToCart()}catch(a){}},doTrackAddToCart:function(){},
trackRemoveFromCart:function(){try{triggermail.Partner.doRemoveFromCart()}catch(a){}},trackCheckoutStart:function(){-1<window.location.pathname.indexOf("checkout_login")&&triggermail.checkout_start({})},trackCheckout:function(){if(-1!=window.location.pathname.indexOf("confirm")&&"undefined"!=typeof nike.checkout.analyticsData){try{if(!(nike.checkout.analyticsData.orderId&&1<=nike.checkout.analyticsData.paymentInfoList.length))return}catch(a){return}try{var b=nike.checkout.analyticsData,c={order_id:b.orderId,
total:triggermail.util.price(b.pricingData.total)},f=[],h=triggermail.util.walkUntil($("#ch4_billingReview")[0],function(a){a=$(a).text().trim();return triggermail.util.findEmail(a)},triggermail.util.isValidEmail);h&&(c.email=h);$.each(b.productList,function(a,b){f.push({id:b.productId})});c.products=f;triggermail.purchase(c);h&&triggermail.identify({email:h})}catch(k){}}},trackSearch:function(){try{if("productgrid"==JSON.parse($(".trackingData").text()).response.pageType){var a=window.location.pathname.split("/").filter(function(a){return a.match(/[a-z]-+/g)});
0<a.length&&triggermail.search({search_term:a[0]})}}catch(b){}try{if(""!=triggermail.util.getUrlParam("sl")){var c=triggermail.util.getUrlParam("sl");triggermail.search({search_term:c})}}catch(f){}nike.deferredListen(nike.Event.GRIDWALL_REFRESH,function(a,b){try{var c=window.location.pathname.split("/").filter(function(a){return a.match(/[a-z]-+/g)});0<c.length&&triggermail.search({search_term:c[0]})}catch(f){}try{if("user typed"==b.onsiteSearchType){var x=b.searchTerm;""!=x&&triggermail.search({search_term:x})}}catch(r){}})},
trackUnsubscribe:function(){if(-1<window.location.href.indexOf("shop,profile"))$(".communication_save_button").on("click",function(){triggermail.util.wrapEvent(function(){$('input[name="receiveEmails"]:visible').is(":checked")||triggermail.unsubscribe({email:$('input[name="email"].edit-email').val()})})()})},trackSubscribe:function(){if(-1<triggermail.util.getUrlParam("l").indexOf("email_signup"))try{$(".exp-profile-email-signup-form button.email-button").on("click",function(a){try{var c=$('.exp-profile-email-signup-form input[name="email"]').val();
triggermail.util.isValidEmail(c)&&triggermail.identify({email:c,source:"email signup"})}catch(f){}})}catch(a){}},watchEmail:function(){try{triggermail.Partner.doWatchEmail()}catch(a){}},doWatchEmail:function(){nike.deferredListen(nike.Event.SUCCESSFUL_USER_LOADED,function(a,b){});nike.deferredListen(nike.Event.REGISTER_SUCCESS,function(a,b){try{"undefined"!=typeof b.response.optIns&&(0<b.response.optIns.length&&b.response.optIns[0].email)&&triggermail.identify({email:b.response.mspEmail,first_name:b.response.firstName,
last_name:b.response.lastName})}catch(c){}});nike.deferredListen(nike.Event.LOGIN_SUCCESS,function(a,b){try{triggermail.identify({email:b.response.email})}catch(c){}});window.triggermail_email_address&&triggermail.identify({email:triggermail_email_address});""!=triggermail.util.getUrlParam("et_e")&&(triggermail.util.isValidEmail(triggermail.util.getUrlParam("et_e"))?triggermail.identify({email:triggermail.util.getUrlParam("et_e")}):triggermail.identify({ingested_id:triggermail.util.getUrlParam("et_e"),
source:"id_append"}))},env:function(){return"drprd-store.nike.com"==window.location.hostname?"d":(-1<window.location.hostname.indexOf("www.nike.com")||-1<window.location.hostname.indexOf("m.nike.com"))&&0!=window.location.hostname.indexOf("ecn")?"p":-1<window.location.hostname.indexOf("store.nike.com")&&0!=window.location.hostname.indexOf("ecn")&&-1<window.location.pathname.indexOf("/us/")?"p":"d"},keys:{lytics:{d:"dev",p:"nike"}}}}();
triggermail.NikeIdFetcher=triggermail.integ.ProductFetcher.extend({id:function(){return nike.globalData.pdpData.productId},url:function(){return window.location.href},name:function(){try{return nike.globalData.pdpData.productTitle}catch(a){}},image:function(){try{return"http://nikeid.nike.com/services/imgredirect/fmt-png-alpha/bgc-na/pbid-"+$("#trackingObject").data("trackingData").product.prebuildId+"/vw-9&amp;loc-en&amp;wid-120&amp;ir-true?"}catch(a){}},price:function(){return triggermail.util.price(nike.globalData.pdpData.formattedListPrice)},
extra_props:function(){var a={},b=$("#trackingObject").data("trackingData").product;a.is_nike_id="true";try{a.primary_sport=triggermail.fetcher.get_primary_sport(!0),a.primary_sport_raw=triggermail.fetcher.get_primary_sport_raw(!0),-1<b.productName.toLowerCase().indexOf("jordan")&&(a.is_jordan="true",a.primary_sport="jordan")}catch(c){}try{a.rating=parseFloat(b.rating)}catch(f){}try{b.onSale&&(a.on_sale=!0)}catch(h){}try{0==b.unlocalizedName.indexOf("W")?a.gender="womens":a.gender="mens"}catch(k){}try{b.product.productId?
(a.style_id=b.productId,a.has_style_id=!0):a.has_style_id=!1}catch(p){}return a}});triggermail.Partner.primarySports="skateboarding;running;basketball;training;football;soccer;golf;tennis;baseball;snowboarding;volleyball;lacrosse;softball;surfing;track and field;yoga;outdoor;hockey;dance;sportswear;NFL;lifestyle".split(";");
triggermail.Partner.primarySportsMap={"baseball / softball":"baseball","training & gym":"training","track & field":"track and field","fitness & training":"training",skateboard:"skateboarding","gym & training":"training","baseball & softball":"baseball",snowboard:"snowboarding",tenis:"tennis",calcio:"football",basket:"basketball",atletica:"track and field","football americano":"NFL","basket-ball":"basketball","entra\u00eenement":"training","athl\u00e9tisme":"track and field","football am\u00e9ricain":"NFL",
"base-ball":"baseball","baseball et softball":"baseball",danse:"dance","fitness et training":"training","f\u00fatbol":"football",baloncesto:"basketball",entrenamiento:"training",atletismo:"track and field","f\u00fatbol americano":"NFL","b\u00e9isbol":"baseball","b\u00e9isbol y softball":"baseball","gym y training":"training",danza:"dance",correr:"running","estilo de vida":"lifestyle","b\u00e1squetbol":"basketball","b\u00e1squet":"basketball","fu\u00dfball":"football",laufen:"running",leichtathletik:"track and field",
"american football":"NFL",tanzen:"dance",freizeit:"lifestyle",hardlopen:"running",voetbal:"football",atletiek:"track and field","fitness en training":"training",skateboarden:"skateboarding",dans:"dance",basketbal:"basketball",snowboarden:"snowboarding","honkbal en softbal":"baseball","\u03c0\u03bf\u03b4\u03cc\u03c3\u03c6\u03b1\u03b9\u03c1\u03bf":"football","\u03c4\u03c1\u03ad\u03be\u03b9\u03bc\u03bf":"running","\u03bc\u03c0\u03ac\u03c3\u03ba\u03b5\u03c4":"basketball","\u03c0\u03c1\u03bf\u03c0\u03cc\u03bd\u03b7\u03c3\u03b7":"training",
"\u03c4\u03ad\u03bd\u03b9\u03c2":"tennis","\u03b3\u03ba\u03bf\u03bb\u03c6":"golf","\u03b1\u03bc\u03b5\u03c1\u03b9\u03ba\u03b1\u03bd\u03b9\u03ba\u03cc \u03c0\u03bf\u03b4\u03cc\u03c3\u03c6\u03b1\u03b9\u03c1\u03bf":"NFL","\u03c3\u03c4\u03af\u03b2\u03bf\u03c2":"track and field","\u03bc\u03c0\u03ad\u03b9\u03b6\u03bc\u03c0\u03bf\u03bb":"baseball","\u03b3\u03b9\u03cc\u03b3\u03ba\u03b1":"yoga","\u03bb\u03b1\u03ba\u03c1\u03cc\u03c2":"lacrosse","\u03b3\u03c5\u03bc\u03bd\u03b1\u03c3\u03c4\u03ae\u03c1\u03b9\u03bf \u03ba\u03b1\u03b9 \u03c0\u03c1\u03bf\u03c0\u03cc\u03bd\u03b7\u03c3\u03b7":"training",
"pi\u0142ka no\u017cna":"football",bieganie:"running","koszyk\u00f3wka":"basketball",trening:"training","futbol ameryka\u0144ski":"NFL","\u0107wiczenia i trening":"training",taniec:"dance","baseball i softball":"baseball",basketbol:"basketball",beyzbol:"baseball",futbol:"football",antrenman:"training","ko\u015fu":"running","amerikan futbolu":"NFL",kaykay:"skateboarding",hokey:"hockey","g\u00fcnl\u00fck giyim":"lifestyle","\u30d0\u30b9\u30b1\u30c3\u30c8\u30dc\u30fc\u30eb":"basketball","\u30e9\u30f3\u30cb\u30f3\u30b0":"running",
"\u30d5\u30c3\u30c8\u30dc\u30fc\u30eb":"football","\u30b5\u30c3\u30ab\u30fc\uff0f\u30d5\u30c3\u30c8\u30dc\u30fc\u30eb":"football","\u30c8\u30ec\u30fc\u30cb\u30f3\u30b0":"training","\u30b9\u30b1\u30fc\u30c8\u30dc\u30fc\u30c9":"skateboard","\u30b9\u30b1\u30fc\u30c8\u30dc\u30fc\u30c7\u30a3\u30f3\u30b0":"skateboarding","\u30b4\u30eb\u30d5":"golf","\u30c6\u30cb\u30b9":"tennis","\u30d9\u30fc\u30b9\u30dc\u30fc\u30eb":"baseball","\u30d9\u30fc\u30b9\u30dc\u30fc\u30eb&\u30bd\u30d5\u30c8\u30dc\u30fc\u30eb":"baseball",
"\u30b9\u30ce\u30fc\u30dc\u30fc\u30c7\u30a3\u30f3\u30b0":"snowboarding","\u30a2\u30e1\u30ea\u30ab\u30f3\u30d5\u30c3\u30c8\u30dc\u30fc\u30eb":"NFL","\u30e8\u30ac":"yoga","\u30e9\u30a4\u30d5\u30b9\u30bf\u30a4\u30eb":"lifestyle"};
triggermail.fetcher.get_primary_sport=function(a){try{var b="sportswear",c;a?c=-1<$("#trackingObject").data("trackingData").product.productName.indexOf("NFL")?"NFL":nike.globalData.pdpData.primarySport.toLowerCase():-1<triggermail.productData.productTitle.indexOf("NFL")?c="NFL":"undefined"!=typeof triggermail.productData.primarySport&&null!=triggermail.productData.primarySport?c=triggermail.productData.primarySport.toLowerCase():null!=triggermail.productData.trackingData&&("undefined"!=typeof triggermail.productData.trackingData.primarySportName&&
null!=triggermail.productData.trackingData.primarySportName)&&(c=triggermail.productData.trackingData.primarySportName.toLowerCase());"undefined"!=typeof triggermail.Partner.primarySportsMap[c]&&(c=triggermail.Partner.primarySportsMap[c]);jQuery.each(triggermail.Partner.primarySports,function(a,f){if(f==c)return b=f,!1});return b}catch(f){return"sportswear"}};
triggermail.fetcher.get_primary_sport_raw=function(a){try{return a?nike.globalData.pdpData.primarySport.toLowerCase():"undefined"!=typeof triggermail.productData.primarySport&&null!=triggermail.productData.primarySport?triggermail.productData.primarySport.toLowerCase():null!=triggermail.productData.trackingData&&"undefined"!=typeof triggermail.productData.trackingData.primarySportName&&null!=triggermail.productData.trackingData.primarySportName?triggermail.productData.trackingData.primarySportName.toLowerCase():
"none"}catch(b){return"none"}};
triggermail.Partner.commonProductView=function(){if(-1<window.location.href.indexOf("m.nike.com")&&"undefined"!=typeof nike.id)setTimeout(function(){triggermail.view({id:productTrackingData.product.productId,is_nike_id:"true"},{partial:!0})},1E3);else if(-1<window.location.href.indexOf("-id-")||-1<window.location.href.indexOf("-id/")){var a=new triggermail.NikeIdFetcher;""!=a.id()&&triggermail.view(a.to_dict())}if("undefined"==typeof $("#trackingObject").data("trackingData")){triggermail.productData=0<
$("#product-data").length?JSON.parse($("#product-data").text()):null;if(0<$(".product-not-found-header").length)try{var b={id:window.location.href.split("?")[0].split("/")[7].split("-")[1],out_of_stock:!0};triggermail.view(b,{partial:!0})}catch(c){}if(void 0!=$('meta[property="og:type"]').attr("content")&&"product"==$('meta[property="og:type"]').attr("content").toLowerCase()&&(a=new triggermail.fetcher,""!=a.id()&&(a=a.to_dict(),-1!=a.image.indexOf("undefined")&&delete a.image,triggermail.view(a)),
10>Math.floor(100*Math.random())&&-1<navigator.userAgent.indexOf("Chrome"))){for(var a=nike.exp.pdp.PdpPage.currentProduct.skuContainer.productSkus,b=[],f=nike.exp.pdp.PdpPage.currentProduct.productId,h=nike.exp.pdp.PdpPage.currentProduct.colorDescription,k=0;k<a.length;k++)b.push({id:f,color:h,size:a[k].displaySize,out_of_stock:!a[k].inStock});triggermail.patch({products:b});nike.deferredListen(nike.Event.INVENTORY_TEMPLATE_RENDER_COMPLETE,function(a,b){try{for(var c=nike.exp.pdp.PdpPage.currentProduct.skuContainer.productSkus,
f=[],h=nike.exp.pdp.PdpPage.currentProduct.productId,k=nike.exp.pdp.PdpPage.currentProduct.colorDescription,w=0;w<c.length;w++)f.push({id:h,color:k,size:c[w].displaySize,out_of_stock:!c[w].inStock});triggermail.patch({products:f})}catch(K){}})}}};
triggermail.Partner.doTrackAddToCart=function(){nike.deferredListen(nike.Event.ADD_TO_CART,function(a,b){triggermail.util.wrapEvent(function(){if("undefined"!=typeof b.product&&"undefined"!=typeof b.product.isNikeId)triggermail.add_to_cart({id:nike.globalData.pdpData.productId});else if("undefined"!=typeof nike.id&&"undefined"!=typeof nike.id.productData.productId)triggermail.add_to_cart({id:nike.id.productData.productId});else{var a=$('meta[property="og:image"]').attr("content"),a=""!=triggermail.util.getParamFromQueryString(a,
"hei")?a.replace(/hei=\d+/,"hei=150"):a+"&hei=150",a=""!=triggermail.util.getParamFromQueryString(a,"wid")?a.replace(/wid=\d+/,"wid=150"):a+"&wid=150";triggermail.add_to_cart({id:b.data.productId,size:b.data.displaySize,color:$(".colorText").text(),image:a})}},b)()})};triggermail.Partner.doCartView=function(){};triggermail.Partner.doRemoveFromCart=function(){};
triggermail.initialize=function(){triggermail.integ.keys={};var a=triggermail.Partner.env();triggermail.integ.keys.lytics=triggermail.Partner.keys.lytics[a];triggermail.integ.debug=!1;triggermail.integ.initServices();triggermail.init();a=triggermail.util.getUrlParam("__distinct_id_override__");""!=a&&(triggermail.lytics.cookie.props.distinct_id=a,triggermail.lytics.cookie.save());a=triggermail.util.getUrlParam("eton_distinct_id");""!=a&&(triggermail.lytics.cookie.props.distinct_id=a,triggermail.lytics.cookie.save());
var a=triggermail.util.getUrlParam("mc_eid"),b=triggermail.lytics.cookie.props.distinct_id;a&&b!==a&&(a="mceid_"+a,b!==a&&(triggermail.merge({merge:{source:b,destination:a},customer:{distinct_id:a}}),triggermail.lytics.cookie.props.distinct_id=a,triggermail.lytics.cookie.save(),triggermail.lytics.register({mc_eid:a})));triggermail.integ.init();a=triggermail.util.getUrlParam("__auto_demo__");""!=a&&(triggermail.demo(),triggermail.identify({email:a}));try{triggermail.eton.init()}catch(c){}};
function __checkJquery(){triggermail.__tm_initialized||(window.jQuery?(triggermail.initialize(),triggermail.__tm_initialized=!0):window.setTimeout(__checkJquery,100))}__checkJquery();
